language: java
sudo: false
addons:
  sonarqube:
    organization: "ndrew-github"
    token:
      secure: "0e3a878376cb853420f840aef4f2ac6e600045a7"
jdk:
  - oraclejdk8
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: travis_retry bundle install
script: bundle exec rake cucumber && mvn sonar:sonar
after_success:
  - mvn clean test jacoco:report coveralls:report
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
